# Generated by Django 4.0.4 on 2023-04-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20221027_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gstin',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
