# Generated by Django 4.0.4 on 2023-04-23 15:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.IntegerField(choices=[(1, 'ELECTRONIC'), (2, 'FURNITURE'), (3, 'CLOTHING')])),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
