# Generated by Django 4.2 on 2023-04-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_addtocart_product_name_addtocart_seller_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='product_name',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_cart', to='api.user'),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_cart', to='api.user'),
        ),
    ]
