# Generated by Django 4.2 on 2023-05-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_addtocart_product_name_addtocart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='ispurchased',
            field=models.BooleanField(default=False),
        ),
    ]
