# Generated by Django 4.0.4 on 2023-05-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_addtocart_seller_id_addtocart_ispurchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers_page', to='api.user'),
        ),
    ]
