# Generated by Django 4.0.4 on 2023-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_addtocart_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='issold',
            field=models.BooleanField(default=False),
        ),
    ]
